apiVersion: v1
kind: ServiceAccount
metadata:
  name: json-server-faker
---
apiVersion: v1
kind: Service
metadata:
  name: json-server-faker
  labels:
    app: json-server-faker
    service: json-server-faker
spec:
  ports:
  - name: http
    port: 8999
    targetPort: 8999
  selector:
    app: json-server-faker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-server-faker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-server-faker
      version: v1
  template:
    metadata:
      labels:
        app: json-server-faker
        version: v1
    spec:
      serviceAccountName: json-server-faker
      containers:
      - image: boreal321/json-server-faker:1.1
        imagePullPolicy: IfNotPresent
        name: json-server-faker
        ports:
        - containerPort: 8999
      imagePullSecrets:
      - name: regcred